"""
Telegram Bot Callback Constants.
Defines callback data string identifiers and prefixes for menu navigation and order placement steps.
"""

# Main Menu Actions
BUY = "BUY"
SELL = "SELL"
MY_ORDERS = "MY_ORDERS"
DEPOSIT = "DEPOSIT"
WITHDRAW = "WITHDRAW"
CONTACT_SALES = "CONTACT_SALES"
BACK_MAIN = "BACK_MAIN"

# Order Placement Flow Callback Prefixes & Actions
BUY_SLOT_PREFIX = "BUY_SLOT_"
SELL_SLOT_PREFIX = "SELL_SLOT_"

QTY_PREFIX = "QTY_"
CUSTOM_QTY = "CUSTOM_QTY"

# Numpad Actions
PAD_DIGIT_PREFIX = "PAD_NUM_"
PAD_DOT = "PAD_DOT"
PAD_DEL = "PAD_DEL"
PAD_OK = "PAD_OK"
PAD_BACK = "PAD_BACK"

CONFIRM_ORDER = "CONFIRM_ORDER"
CONFIRM_DEPOSIT = "CONFIRM_DEPOSIT"
DEPOSIT_BANK = "DEPOSIT_BANK"
DEPOSIT_CASH = "DEPOSIT_CASH"
WITHDRAW_BANK = "WITHDRAW_BANK"
WITHDRAW_CASH = "WITHDRAW_CASH"
SKIP_DEPOSIT_DOC = "SKIP_DEPOSIT_DOC"
CANCEL_ORDER = "CANCEL_ORDER"
CALL_SALES_PHONE = "CALL_SALES_PHONE"